### ISSUE TITLE
ERROR com.netflix.conductor.client.automator.TaskPollExecutor - Error when polling for tasks io.orkes.conductor.client.http.ApiException:

### ISSUE THREAD

**Issue by alberttwong** [conductor-sdk/java-sdk-examples#4]
```
(base) albertwong@M-C02D5GVKMD6M java-sdk-examples % ./gradlew run

> Task :run
10:53:29.104 [pool-6-thread-2] ERROR com.netflix.conductor.client.automator.TaskPollExecutor - Error when polling for tasks
io.orkes.conductor.client.http.ApiException: 403:{"timestamp":"2023-02-04T18:53:29.187+00:00","status":"403","error":"Forbidden","exception":"org.springframework.security.access.AccessDeniedException","message":"Forbidden","path":"/api/tasks/poll/batch/send_sms","host":"orkes-conductor-deployment-5d5689695f-zjjmn","cause":"Forbidden"}
        at io.orkes.conductor.client.ApiClient.handleResponse(ApiClient.java:874) ~[orkes-conductor-client-1.1.5.jar:?]
        at io.orkes.conductor.client.ApiClient.execute(ApiClient.java:824) ~[orkes-conductor-client-1.1.5.jar:?]
        at io.orkes.conductor.client.http.api.TaskResourceApi.batchPollWithHttpInfo(TaskResourceApi.java:419) ~[orkes-conductor-client-1.1.5.jar:?]
        at io.orkes.conductor.client.http.api.TaskResourceApi.batchPoll(TaskResourceApi.java:397) ~[orkes-conductor-client-1.1.5.jar:?]
        at io.orkes.conductor.client.http.OrkesTaskClient.batchPollTasksInDomain(OrkesTaskClient.java:82) ~[orkes-conductor-client-1.1.5.jar:?]
        at io.orkes.conductor.client.http.OrkesTaskClient.pollTask(OrkesTaskClient.java:66) ~[orkes-conductor-client-1.1.5.jar:?]
        at com.netflix.conductor.client.automator.TaskPollExecutor.lambda$pollAndExecute$2(TaskPollExecutor.java:148) ~[conductor-client-3.9.0-orkes-g.jar:3.9.0-orkes-g]
        at com.netflix.spectator.api.SwapTimer.record(SwapTimer.java:43) ~[spectator-api-1.3.7.jar:1.3.7]
        at com.netflix.conductor.client.automator.TaskPollExecutor.pollAndExecute(TaskPollExecutor.java:146) ~[conductor-client-3.9.0-orkes-g.jar:3.9.0-orkes-g]
        at com.netflix.conductor.client.automator.TaskRunnerConfigurer.lambda$init$0(TaskRunnerConfigurer.java:262) ~[conductor-client-3.9.0-orkes-g.jar:3.9.0-orkes-g]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
10:53:29.285 [pool-6-thread-2] ERROR com.netflix.conductor.client.automator.TaskPollExecutor - Error when polling for tasks
io.orkes.conductor.client.http.ApiException: 403:{"timestamp":"2023-02-04T18:53:29.342+00:00","status":"403","error":"Forbidden","exception":"org.springframework.security.access.AccessDeniedException","message":"Forbidden","path":"/api/tasks/poll/batch/send_sms","host":"orkes-conductor-deployment-5d5689695f-l44ft","cause":"Forbidden"}
        at io.orkes.conductor.client.ApiClient.handleResponse(ApiClient.java:874) ~[orkes-conductor-client-1.1.5.jar:?]
        at io.orkes.conductor.client.ApiClient.execute(ApiClient.java:824) ~[orkes-conductor-client-1.1.5.jar:?]
        at io.orkes.conductor.client.http.api.TaskResourceApi.batchPollWithHttpInfo(TaskResourceApi.java:419) ~[orkes-conductor-client-1.1.5.jar:?]
        at io.orkes.conductor.client.http.api.TaskResourceApi.batchPoll(TaskResourceApi.java:397) ~[orkes-conductor-client-1.1.5.jar:?]
        at io.orkes.conductor.client.http.OrkesTaskClient.batchPollTasksInDomain(OrkesTaskClient.java:82) ~[or
```

**Comment by alberttwong** [comment]
The answer is that there are a bunch of sample tasks.  You'll have to delete the ones you don't want (mostly the ones that require connectivity to an external service).
